### ISSUE TITLE
No static linking support

### ISSUE THREAD

**Issue by Temtaime** [Calrama/llvm-d#14]
For example on windows there's no way official way buiding llvm as a shared library.

**Comment by Calrama** [comment]
I have no intention of supporting static linking. That's what `deimos-llvm` was for (which is older than `llvm-d`). Building a shared library on Windows was possible [four years ago](https://llvm.org/bugs/show_bug.cgi?id=12795) and I have [no reason](https://reviews.llvm.org/D5036) to suspect that it does not work anymore.

**Comment by Temtaime** [comment]
Why not?
If we make a version LLVM_STATIC there's no code breakage and we would support both static and shared linking.
I can create a PR.

**Comment by Calrama** [comment]
I already gave you a reason I consider sufficient:
> That's what deimos-llvm was for (which is older than llvm-d)

`llvm-d` was created specifically to support dynamic linking against LLVM.
If you, however, do not consider that sufficient, here are some others (in no particular order):
- Even if you write the feature code, by accepting it it becomes my responsibility to maintain it, i.e. there's a long-term, continuous cost (time) that I would have to pay.
- While there's different opinions on [static](https://www.akkadia.org/drepper/no_static_linking.html) vs [dynamic](http://harmful.cat-v.org/software/dynamic-linking/) linking, when it comes to libraries of significant object size (such as LLVM) I consider the issues (especially the first two listed on the former of the two previous links) with static linking unacceptable and do not want to participate in enabling its use.
- Code is a liability, not an asset. One can most likely already accomplish one's actual goal with the current code base using shared linking (even on Windows), so why should I accept more liability for (from my perspective) zero benefit.

**Comment by Temtaime** [comment]
The deimoa library is outdated and not mantained.
Ok, i'll just fork llvm-d then.

**Comment by Calrama** [comment]
Then I would think that adopting and updating the deimos library makes more sense, since static linking against LLVM was its purpose.
Or just use dynamic linking. So far the only reason you've given was that dynamic linking on Windows isn't *officially* supported (which, if it didn't actually work, would be an LLVM issue to fix there, not here). Do you have a well-founded reason (other than "no official support") not to use (working) dynamic linking?
In any case, while there's no need to inform me about forking `llvm-d`, thanks for the heads up.

**Comment by Calrama** [comment]
`s/dynamic linking/dynamic loading` in the above, of course.
