### ISSUE TITLE
Some functions are missing

### ISSUE THREAD

**Issue by Temtaime** [Calrama/llvm-d#15]
There's no
LLVMLinkInMCJIT
LLVMLinkInInterpreter
functions(maybe others ?).

**Comment by Calrama** [comment]
A PR for this would be welcome.

**Comment by Calrama** [comment]
On further investigation it doesn't seem to me that those missing functions actually have some runtime functionality, but exists for static linking purposes. Since `llvm-d` does not support static linking, I see no reason to include them.
If you think they do have runtime functionality, please reopen the issue and explain why.
If you do find (other) missing functions that have runtime functionality, please open another issue.
