### ISSUE TITLE
Cannot link with LLVM with example

### ISSUE THREAD

**Issue by zhaopuming** [Calrama/llvm-d#17]
I have to manually add lflags after libs in dub.json

```
"libs": ["LLVM"],
"lflags": ["-L/usr/lib/llvm-3.8/lib/"]
```

for it to compile.

**Comment by Calrama** [comment]
Well, if your linux distribution doesn't install the LLVM library/libraries into a path that your linker searches by default that's to be expected, which is why the release notes read
> **you** need to **link against** the correct libraries from this release onwards
> a good **starting point** would be examples/fibonacci/dub.json

"link against" includes setting the correct paths so your linker actually finds them (which is exactly what `-L/path/to/llvm` does). The release notes state that it's your responsibility to take care of it. What exactly do you want to be done?

**Comment by zhaopuming** [comment]
Sorry I didn't see this release note, only saw what is in the README.md, where it says:

```
To use llvm-d you need only import it, after which all of LLVM's C API's functions should be available.
```

without mentioning linking. Maybe you can add that description to README?

**Comment by Calrama** [comment]
Done: https://github.com/Calrama/llvm-d/commit/430cad214342f668758be3d45300d598bb1320b2
